name: scretask
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  dotted_border: ^2.0.0+2
  flutter:
    sdk: flutter
  lottie: ^1.3.0
  provider: ^6.0.3
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/animation/

  fonts:
    - family: Averta
      fonts:
        - asset: assets/fonts/AvertaExtraBold.otf
        - asset: assets/fonts/AvertaRegular.otf
