name: scretask
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  cloudinary_sdk: ^4.0.1+9
  cupertino_icons: ^1.0.2
  custom_navigation_bar: ^0.8.2
  date_picker_timeline: ^1.2.3
  dotted_border: ^2.0.0+2
  file_picker: ^4.6.0
  flutter:
    sdk: flutter
  flutter_switch: ^0.3.2
  http: ^0.13.4
  intl: ^0.17.0
  local_auth: ^2.1.0
  lottie: ^1.3.0
  pie_chart: ^5.3.1
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  url_strategy: ^0.2.0

dev_dependencies:
  device_preview: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/animation/
    - assets/images/

  fonts:
    - family: Averta
      fonts:
        - asset: assets/fonts/AvertaExtraBold.otf
        - asset: assets/fonts/AvertaRegular.otf
